services:
  enset-ebank-discovery-service:
    build: ./discovery-service
    container_name: enset-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  enset-ebank-config-service:
    build: ./config-service
    container_name: enset-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-discovery-service:
        condition: service_healthy
  enset-customer-service:
    build: ./customer-service
    container_name: enset-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-ebank-config-service:
        condition: service_healthy
  enset-account-service:
    build: ./account-service
    container_name: enset-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    depends_on:
      enset-customer-service:
        condition: service_healthy
  enset-gateway-service:
    build: ./gateway-service
    container_name: enset-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
    depends_on:
      enset-ebank-config-service:
        condition: service_healthy
  front-send-angular:
    build: ./angular-front-end
    container_name: front-send-angular
    ports:
      - '82:80'
    expose:
      - '82'